apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 192.168.56.10:8083/nodemongoapp:6.0  # Your Nexus image
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://root:example@mongodb:27017"
      - name: mongodb
        image: mongo:4.2
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "example"